### ISSUE TITLE
java.util.List.size() because zipsForCity

### ISSUE THREAD

**Issue by AmmarFaiq** [synthetichealth/synthea#1046]
### What happened?

Guys, I found this during the run of the simulation. Even though it can produce most people, sometimes this error log shows. Any ideas why such errors happened?

Thanks,

### Environment

```markdown
- OS: Windows 10
- Java: JDK 18
```

### Relevant log output

```shell
java.util.concurrent.ThreadPoolExecutor@70a898b0[Shutting down, pool size = 16, active threads = 16, queued tasks = 2883, completed tasks = 7101]

and 

java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "zipsForCity" is null
        at org.mitre.synthea.world.geography.Location.assignPoint(Location.java:375)
        at org.mitre.synthea.modules.LifecycleModule.birth(LifecycleModule.java:168)
        at org.mitre.synthea.engine.Generator.createPerson(Generator.java:661)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:477)
        at org.mitre.synthea.engine.Generator.lambda$run$3(Generator.java:367)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by jawalonoski** [comment]
What state and/or city are you running?

**Comment by jawalonoski** [comment]
This is occurring because there are no zip codes for the area being simulated, as per the https://github.com/synthetichealth/synthea/blob/master/src/main/resources/geography/zipcodes.csv file.

It would help if you could tell us what location you were running, so we could try to track down the missing zip code.

In the meantime, I can add a null check on `zipsForCity`.

**Comment by jawalonoski** [comment]
I'm going to close this issue because we made a patch that should stop the program from crashing, but on the other hand, you didn't tell us what city or state you were running so we could properly debug the issue.... so, reopen this if you see it again.
