### ISSUE TITLE
Incompatibility with synthea-international

### ISSUE THREAD

**Issue by willdalh** [synthetichealth/synthea#1162]
### What happened?

Hi! 

Starting from this [commit](https://github.com/synthetichealth/synthea/commit/0afa939928eda3daca0e58313a5e502895c6cb21), I am unable to generate data after merging with the Norwegian data from synthea-international. The error seems to be `org.mitre.synthea.world.agents.PayerManager` reading CSV-files that are not compatible when using states and cities outside the US. I managed to fix the problem by adding Oslo and some random values to different CSV-files to make Oslo a valid state/county. Looking at other country subdirectories from synthea-international, it seems like they also miss the required data. 

The log output is produced by running `./run_synthea Oslo` after merging with the Norwegian data.

### Environment

```markdown
- OS: Windows 10 21H2
- Java: java 18.0.1.1 2022-04-22
```

### Relevant log output

```shell
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1396)       
        at com.google.common.io.Resources.getResource(Resources.java:197)
        at org.mitre.synthea.helpers.Utilities.readResource(Utilities.java:414)     
        at org.mitre.synthea.helpers.Utilities.readResourceAndStripBOM(Utilities.java:428)
        at org.mitre.synthea.world.agents.behaviors.planeligibility.PlanEligibilityFinder.buildPlanEligibilities(PlanEligibilityFinder.java:56)
        at org.mitre.synthea.world.agents.PayerManager.loadPayers(PayerManager.java:94)
        at org.mitre.synthea.engine.Generator.init(Generator.java:267)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:208)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:184)
        at App.main(App.java:229)
```

**Comment by jawalonoski** [comment]
Thank you for the bug report. A recent update seems to have broken some of the synthea-international configurations. We'll investigate.

**Comment by jawalonoski** [comment]
Bug fix pending review and merge: https://github.com/synthetichealth/synthea-international/pull/16

**Comment by jawalonoski** [comment]
This should be resolved.

**Comment by willdalh** [comment]
Thank you alot, the issue has been resolved.

**Comment by willdalh** [comment]
Thank you alot, the issue has been resolved.
