### ISSUE TITLE
Can not build successfully 

### ISSUE THREAD

**Issue by ZiyiWan** [synthetichealth/synthea#1199]
### What happened?

Can not building the project when I tried to run this command:
./gradlew build check test

### Environment

```markdown
- OS:macOS 12.6
- Java:java 19.0.1
```

### Relevant log output

```shell
FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/zwan0411/Downloads/synthea/settings.gradle'

* What went wrong:
Could not compile settings file '/Users/zwan0411/Downloads/synthea/settings.gradle'.
> startup failed:
  General error during conversion: Unsupported class file major version 63
```

**Comment by agiani99** [comment]
Hi all
same environment and same error surfaced.
here the details:
`org.mitre.synthea.identity.EntityManagerTest > endToEnd FAILED
    java.nio.file.NoSuchFileException: C:\Users\ANDREA~1.ZAL\AppData\Local\Temp\junit10684904934687616346\junit10799634764585537561\json
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:86)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:535)
        at java.base/java.nio.file.Files.newDirectoryStream(Files.java:482)
        at java.base/java.nio.file.Files.list(Files.java:3791)
        at org.mitre.synthea.identity.EntityManagerTest.endToEnd(EntityManagerTest.java:84)
`

**Comment by gherka** [comment]
Had the same issue, but installing Java 17 JDK rather than 19 solved it for me.

**Comment by r0sies** [comment]
I had the same error with java 17.0.5 2022-10-18 LTS

java.nio.file.NoSuchFileException: C:\Users\rosem\AppData\Local\Temp\junit2771736295103762717\junit2100710100030913382\json
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:86)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:535)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:482)
	at java.base/java.nio.file.Files.list(Files.java:3792)
	at org.mitre.synthea.identity.EntityManagerTest.endToEnd(EntityManagerTest.java:84)

java --version
java 17.0.5 2022-10-18 LTS
Java(TM) SE Runtime Environment (build 17.0.5+9-LTS-191)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)

**Comment by jawalonoski** [comment]
The Java 17 error might have been fixed with #1215. Can someone verify or refute?

For Java 19, the version of Gradle would need to be updated to at least Gradle 7.6. See https://docs.gradle.org/current/userguide/compatibility.html. You could manually do this by modifying this line:
https://github.com/synthetichealth/synthea/blob/5f3ad98666a9e2976ea589417d59393eaae2b2ca/gradle/wrapper/gradle-wrapper.properties#L3

**Comment by aayushL** [comment]
I am facing the same issue. tried with java 17 and then with 19 as well. Can someone help me with this? I am trying to build on windows 10

**Comment by agiani99** [comment]
Using Java 19 and gradle 7.6 within synthea/gradle/wrapper/gradle-wrapper.properties, I was not able to build, not because of compiling but because 
org.mitre.synthea.identity.EntityManagerTest > endToEnd FAILED
Any hint for me?
Thanks a lot @jawalonoski, anyway.

**Comment by aayushL** [comment]
> Using Java 19 and gradle 7.6 within synthea/gradle/wrapper/gradle-wrapper.properties, I was not able to build, not because of compiling but because org.mitre.synthea.identity.EntityManagerTest > endToEnd FAILED Any hint for me? Why gradle output a FAILURE? However, the build seems to work anyway. A bit confusing to me. the command which worked was: run_synthea -p 1000 -m asthma , it really output CSV cohort as requested per synthea.properties edited file. Thanks a lot @jawalonoski, anyway.

I got the same error
