### ISSUE TITLE
US Core 3.1

### ISSUE THREAD

**Issue by garyisaac** [synthetichealth/synthea#1365]
### What happened?

Synthea throws an error when configuring a properties file to use US Core 3.1. US Core 4 and 5 work. Please let me know if Synthea still supports US Core 3.

exporter.fhir.us_core_version = 3.1

### Environment

```markdown
- OS: Windows 10
- Java:
```

### Relevant log output

```shell
49 -- Elenora790 Legros616 (70 y/o F) Boston, Massachusetts  (147111)
java.lang.NullPointerException
        at org.mitre.synthea.export.FhirR4.observation(FhirR4.java:1873)
        at org.mitre.synthea.export.FhirR4.convertToFHIR(FhirR4.java:432)
        at org.mitre.synthea.export.FhirR4.convertToFHIRJson(FhirR4.java:527)
        at org.mitre.synthea.export.Exporter.exportRecord(Exporter.java:269)
        at org.mitre.synthea.export.Exporter.export(Exporter.java:188)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:541)
        at org.mitre.synthea.engine.Generator.lambda$run$3(Generator.java:383)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by fmatten** [comment]
A number for the "where possible" boundary, in case it is useful here.

We generated the `10YearsMcodeBreast` scenario and looked at how far mCODE profiling reaches into the output. Of the observations that are oncologically meaningful in that run, **1,412 carry no `meta.profile` at all** — not a wrong profile, none.

This is not a report that something is broken. The module says it follows mCODE *where possible*, and that phrase is doing real work: a receiver filtering by mCODE profile simply will not see those resources, which is a consequence of the stated boundary rather than a departure from it.

What might be worth knowing is where the boundary is meant to run — whether profiling is expected on the resources a disease module emits directly, or only on the ones mCODE names explicitly. If that is written down somewhere we missed, a pointer is all we need.

Method, briefly: one generation run, counted on the FHIR output; no claim about other scenarios or releases.
