### ISSUE TITLE
Condition Lookup Failure

### ISSUE THREAD

**Issue by jawalonoski** [synthetichealth/synthea#141]
Ran across this issue exporting a FHIR record...
```
[2017-02-01 15:25:48] 2276: Romaguera268, Izabella217. Hispanic Puerto rican. 44 y/o F 223 lbs. -- Diabetic
undefined method `[]' for nil:NilClass
/Users/jwalonoski/git/synthea/lib/records/fhir.rb:255:in `observation'
/Users/jwalonoski/git/synthea/lib/records/fhir.rb:21:in `block (2 levels) in convert_to_fhir'
/Users/jwalonoski/git/synthea/lib/records/fhir.rb:16:in `each'
/Users/jwalonoski/git/synthea/lib/records/fhir.rb:16:in `block in convert_to_fhir'
/Users/jwalonoski/git/synthea/lib/records/fhir.rb:12:in `each'
/Users/jwalonoski/git/synthea/lib/records/fhir.rb:12:in `convert_to_fhir'
/Users/jwalonoski/git/synthea/lib/records/exporter.rb:26:in `export'
/Users/jwalonoski/git/synthea/lib/world/sequential.rb:93:in `block in run_random'
/Users/jwalonoski/git/synthea/lib/world/sequential.rb:237:in `run_task'
/Users/jwalonoski/git/synthea/lib/world/sequential.rb:90:in `run_random'
/Users/jwalonoski/git/synthea/lib/world/sequential.rb:61:in `run'
lib/tasks/tasks.rake:57:in `block (2 levels) in <top (required)>'
```

Relates to this bit of code trying to reference a condition that doesn't exist:
```ruby
        if obs_data[:value_type] == 'condition'
          condition_data = COND_LOOKUP[observation['value']]
          entry.resource.valueCodeableConcept = FHIR::CodeableConcept.new('coding' => [{
                                                                            'code' => condition_data[:codes]['SNOMED-CT'][0],
                                                                            'display' => condition_data[:description],
                                                                            'system' => 'http://snomed.info/sct'
                                                                          }])
```

**Comment by jawalonoski** [comment]
This bug occurs when someone dies of a condition which has not yet been diagnosed (globally across all patients), and a death certificate is being issued referencing a condition which hasn't been added to the `COND_LOOKUP` table... values are typically entered into that lookup table dynamically when they are diagnosed.
