### ISSUE TITLE
Method 'old_init' not defined in SortedSet

### ISSUE THREAD

**Issue by cjduffett** [synthetichealth/synthea#156]
Encountered the following runtime error during the latests sequential run. Stack trace:

```
method 'old_init' not defined in SortedSet
org/jruby/RubyModule.java:2840:in `remove_method'
/Users/cduffett/.rvm/rubies/jruby-9.1.2.0/lib/ruby/stdlib/set.rb:686:in `block in setup'
org/jruby/RubyModule.java:2790:in `module_eval'
/Users/cduffett/.rvm/rubies/jruby-9.1.2.0/lib/ruby/stdlib/set.rb:684:in `setup'
/Users/cduffett/.rvm/rubies/jruby-9.1.2.0/lib/ruby/stdlib/set.rb:694:in `initialize'
/Users/cduffett/.rvm/gems/jruby-9.1.2.0/gems/chunky_png-1.3.8/lib/chunky_png/palette.rb:22:in `initialize'
/Users/cduffett/.rvm/gems/jruby-9.1.2.0/gems/chunky_png-1.3.8/lib/chunky_png/palette.rb:67:in `from_canvas'
/Users/cduffett/.rvm/gems/jruby-9.1.2.0/gems/chunky_png-1.3.8/lib/chunky_png/canvas.rb:269:in `palette'
/Users/cduffett/.rvm/gems/jruby-9.1.2.0/gems/chunky_png-1.3.8/lib/chunky_png/canvas/png_encoding.rb:124:in `determine_png_encoding'
/Users/cduffett/.rvm/gems/jruby-9.1.2.0/gems/chunky_png-1.3.8/lib/chunky_png/canvas/png_encoding.rb:75:in `to_datastream'
/Users/cduffett/.rvm/gems/jruby-9.1.2.0/gems/chunky_png-1.3.8/lib/chunky_png/image.rb:62:in `to_datastream'
/Users/cduffett/.rvm/gems/jruby-9.1.2.0/gems/chunky_png-1.3.8/lib/chunky_png/canvas/png_encoding.rb:50:in `to_blob'
/Users/cduffett/github/synthea/lib/records/fhir.rb:142:in `basic_info'
/Users/cduffett/github/synthea/lib/records/fhir.rb:11:in `convert_to_fhir'
/Users/cduffett/github/synthea/lib/records/exporter.rb:26:in `export'
/Users/cduffett/github/synthea/lib/world/sequential.rb:215:in `block in process_person'
/Users/cduffett/github/synthea/lib/world/sequential.rb:327:in `block in run_task'
/Users/cduffett/.rvm/gems/jruby-9.1.2.0/gems/concurrent-ruby-1.0.4-java/lib/concurrent/executor/java_executor_service.rb:94:in `run'
```

Looks to be an issue with the png gem we're using for the fingerprints, but it's not happening for every patient.

**Comment by cjduffett** [comment]
It's been 2 months, has anyone observed this recently?

**Comment by dehall** [comment]
Looks like it's really an issue with the ruby Set/SortedSet class not being threadsafe. This other project's issue talks about it a little bit:   https://github.com/socketry/timers/issues/20  

So this will only happen when running multithreaded on JRuby, and even then it looks like it can only happen within the first few patients

**Comment by jawalonoski** [comment]
OBE
