### ISSUE TITLE
Generic Module Error

### ISSUE THREAD

**Issue by jawalonoski** [synthetichealth/synthea#157]
```
NoMethodError: undefined method `to_sym' for nil:NilClass
Did you mean?  to_s
/Users/jwalonoski/git/synthea/lib/generic/states.rb:458:in `end_prescription'
/Users/jwalonoski/git/synthea/lib/generic/states.rb:452:in `process'
/Users/jwalonoski/git/synthea/lib/generic/states.rb:36:in `run'
/Users/jwalonoski/git/synthea/lib/generic/context.rb:31:in `run'
/Users/jwalonoski/git/synthea/lib/generic/context.rb:50:in `run'
/Users/jwalonoski/git/synthea/lib/modules/generic.rb:54:in `block (2 levels) in <class:Generic>'
/Users/jwalonoski/git/synthea/lib/modules/generic.rb:49:in `each'
/Users/jwalonoski/git/synthea/lib/modules/generic.rb:49:in `block in <class:Generic>'
/Users/jwalonoski/git/synthea/lib/modules/module.rb:10:in `call'
/Users/jwalonoski/git/synthea/lib/modules/module.rb:10:in `block in run'
/Users/jwalonoski/git/synthea/lib/modules/module.rb:10:in `each'
/Users/jwalonoski/git/synthea/lib/modules/module.rb:10:in `run'
/Users/jwalonoski/git/synthea/lib/modules/module.rb:18:in `block in apply'
/Users/jwalonoski/git/synthea/lib/modules/module.rb:18:in `each'
/Users/jwalonoski/git/synthea/lib/modules/module.rb:18:in `apply'
/Users/jwalonoski/git/synthea/lib/world/sequential.rb:274:in `build_person'
/Users/jwalonoski/git/synthea/lib/world/sequential.rb:169:in `run_random'
/Users/jwalonoski/git/synthea/lib/world/sequential.rb:83:in `run'
```

**Comment by jawalonoski** [comment]
Added some debugging to find:
```
FATAL ERROR State: Ear_Infection_OTC_Painkiller_End
FATAL ERROR in Module: ear_infections
```
