### ISSUE TITLE
CCDA generation broken

### ISSUE THREAD

**Issue by chrisgrenz** [synthetichealth/synthea#270]
Running with default options and ccda generation on produces the following:

```The following has evaluated to null or missing:
==> preferredAmbulatoryProvider.attributes.name  [in template "ccda.ftl" at line 51, column 17]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
        - Failed at: ${preferredAmbulatoryProvider.attribu...  [in template "ccda.ftl" at line 51, column 15]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
        at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
        at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:465)
        at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:387)
        at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:356)
        at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:96)
        at freemarker.core.DollarVariable.accept(DollarVariable.java:59)
        at freemarker.core.Environment.visit(Environment.java:326)
        at freemarker.core.Environment.visit(Environment.java:332)
        at freemarker.core.Environment.process(Environment.java:305)
        at freemarker.template.Template.process(Template.java:378)
        at org.mitre.synthea.export.CCDAExporter.export(CCDAExporter.java:97)
        at org.mitre.synthea.export.Exporter.export(Exporter.java:61)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:296)
        at org.mitre.synthea.engine.Generator.lambda$run$0(Generator.java:163)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.base/java.lang.Thread.run(Thread.java:844)
{alive=10, dead=1}
```

**Comment by gteichrow** [comment]
I'm seeing that error as well. As far as I can tell, it looks like at the time o the call to CCDAExporter.export() the person does have an "preferredAmbulatoryProvider" attribute just fine.  And that object, a Provider, is valid.  The problem is that the Attributes for that Provider have not be populated.  Attributes.size=0.  Im wonder if the attributes should be set/populated when all the providers are marshalled at startup?

**Comment by gteichrow** [comment]
In debug mode can confirm that at time of call to Exporter.export(person, time); in Generator.generatePerson(296) person looks good and the Ambulatory provider looks cool exception for the attributes.

Here is a screenshot from the debugger:

https://d.pr/free/i/XqkW0X

**Comment by gteichrow** [comment]
Alrighty.  Possible solution or at least workaround.  If you change ccda.ftl to refer to templated variables to say ${preferredAmbulatoryProvider.name} instead of ${preferredAmbulatoryProvider.attributes.name} then generation seems to work fine.
