### ISSUE TITLE
Running synthea in Eclipse has some error

### ISSUE THREAD

**Issue by meSmashsta** [synthetichealth/synthea#353]
Is this normal?

```
java.lang.IllegalArgumentException: resource version.txt not found.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:204)
	at com.google.common.io.Resources.getResource(Resources.java:197)
	at org.mitre.synthea.helpers.Utilities.readResource(Utilities.java:213)
	at org.mitre.synthea.helpers.Utilities.getSyntheaVersion(Utilities.java:195)
	at org.mitre.synthea.helpers.Utilities.<clinit>(Utilities.java:188)
	at org.mitre.synthea.world.geography.Location.loadAbbreviations(Location.java:195)
	at org.mitre.synthea.world.geography.Location.<clinit>(Location.java:18)
	at org.mitre.synthea.engine.Generator.init(Generator.java:146)
	at org.mitre.synthea.engine.Generator.<init>(Generator.java:115)
	at App.main(App.java:83)
```

**Comment by dehall** [comment]
It's not intentional but can happen on a clean copy. We use a gradle task to get the version tag and put it in a resources file. Running the app in Eclipse bypasses this task. The only place the version tag is used is in exported records, but there's a default version that will get used if the file isn't there.

Running `run_synthea` once, or the specific gradle task `./gradlew versionTxt` (or `.\gradlew.bat versionTxt` on Windows) will generate the file and prevent this error in the future.
