### ISSUE TITLE
Error when executing ./run_synthea in the command line (on MAC OS X 10.13.5)

### ISSUE THREAD

**Issue by AMDonati** [synthetichealth/synthea#356]
After having downloaded synthea, when I want to download the data using "./run_synthea" in the command line, I get the following error (I am using Mac OS X version 10.13.5): 

`Exception in thread "main" javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty`

---Next lines of the error message: 
```
Exception in thread "main" javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at com.sun.net.ssl.internal.ssl.Alerts.getSSLException(Alerts.java:190)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1747)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1708)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1691)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1222)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1199)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:476)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:166)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1195)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:234)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
	at org.gradle.wrapper.Download.download(Download.java:51)
	at org.gradle.wrapper.Install$1.call(Install.java:62)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.RuntimeException:
```

**Comment by dehall** [comment]
From what I can tell from various sources online, this may be an issue with your JDK certificate store. Which version of java are you running? Run `java --version` at a command line. 

Unfortunately there are a lot of different suggestions on how to resolve this but they are not consistent across operating systems, ex: https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty

The simplest fix is likely just to re-install Java, I recommend either JDK 8 or 10. http://www.oracle.com/technetwork/java/javase/downloads/jdk10-downloads-4416644.html

**Comment by AMDonati** [comment]
Thanks, downloading JDK 10 solved my problem!
