### ISSUE TITLE
Generating records exception

### ISSUE THREAD

**Issue by meSmashsta** [synthetichealth/synthea#438]
Hi guys, I've run the following command:

./run_synthea -p 10000

And during generation, I saw an error occurred, I have the latest version of synthea as of this writing.

![screenshot from 2018-10-24 09-41-47](https://user-images.githubusercontent.com/12151336/47400808-66c0fc80-d771-11e8-9e41-78bcc5ff53c2.png)

**Comment by jawalonoski** [comment]
Tried to recreate this, only took a few seconds...

```
java.lang.ArrayIndexOutOfBoundsException: -29
        at java.util.Arrays$ArrayList.get(Arrays.java:3841)
        at org.mitre.synthea.modules.HealthInsuranceModule.getCurrentInsurance(HealthInsuranceModule.java:113)
        at org.mitre.synthea.world.concepts.HealthRecord$Claim.<init>(HealthRecord.java:255)
        at org.mitre.synthea.world.concepts.HealthRecord$Encounter.<init>(HealthRecord.java:333)
        at org.mitre.synthea.world.concepts.HealthRecord.encounterStart(HealthRecord.java:535)
        at org.mitre.synthea.engine.State$Encounter.process(State.java:501)
        at org.mitre.synthea.engine.State.run(State.java:145)
        at org.mitre.synthea.engine.Module.process(Module.java:179)
        at org.mitre.synthea.engine.Module.process(Module.java:187)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:281)
        at org.mitre.synthea.engine.Generator.lambda$run$0(Generator.java:197)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
