### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException on HEAD

### ISSUE THREAD

**Issue by shabiel** [synthetichealth/synthea#542]
Java 11 related?

```
$ rm -r output/; ./run_synthea --exporter.fhir_stu3.export true -a 40-140 --exporter.years_of_history 0 --exporter.text.export true -p 100 Utah
```

```
java.lang.ArrayIndexOutOfBoundsException: Index 128 out of bounds for length 128
        at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4351)
        at org.mitre.synthea.modules.HealthInsuranceModule.process(HealthInsuranceModule.java:56)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:319)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:235)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

```
sam@ibis:~/workspace/repo/synthea$ java --version
openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)
```

**Comment by jawalonoski** [comment]
Not a Java 11 error.

It seems that someone lived to the age of 129 years old... which I've never seen before, because it is extremely unlikely... and was trying to buy insurance in the Insurance Module.

The insurance module assumes (poorly, apparently) that no one will live that long and so has a fixed size array (of 128).

**Comment by jawalonoski** [comment]
Do you know what seed was used? It should be in the output if you still have that console window open.

**Comment by shabiel** [comment]
```
Running with options:
Population: 100
Seed: 1563205606697
Provider Seed:1563205606697
Location: Utah
Min Age: 40
Max Age: 140
```
