### ISSUE TITLE
Payer related NPE

### ISSUE THREAD

**Issue by jawalonoski** [synthetichealth/synthea#558]
Merging Payers into the software has introduced a very rare NPE:
```
java.lang.NullPointerException
        at org.mitre.synthea.export.FhirR4.encounterClaim(FhirR4.java:816)
        at org.mitre.synthea.export.FhirR4.convertToFHIR(FhirR4.java:271)
        at org.mitre.synthea.export.FhirR4.convertToFHIRJson(FhirR4.java:289)
        at org.mitre.synthea.export.Exporter.exportRecord(Exporter.java:112)
        at org.mitre.synthea.export.Exporter.export(Exporter.java:52)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:396)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:239)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

It occurs when trying to export Payer information when the payer is null.

https://github.com/synthetichealth/synthea/blob/a36e1f519d2051fed4a2bc9daf779dfb25f9c931/src/main/java/org/mitre/synthea/export/FhirR4.java#L810-L816

https://github.com/synthetichealth/synthea/blob/a36e1f519d2051fed4a2bc9daf779dfb25f9c931/src/main/java/org/mitre/synthea/world/agents/Person.java#L545-L550

In certain rare cases, the Payer is not getting set.

**Comment by jawalonoski** [comment]
OK, so it seems to be happening when the patient dies within the span of a timestep of their birthday (i.e. within 7 days).

Payers get selected each year during the first timestep at or after a patients birthday.

So, the patient is dying just before they get insurance updated for their current age.
