### ISSUE TITLE
alive=0 dead=0

### ISSUE THREAD

**Issue by BYHealthCat** [synthetichealth/synthea#599]
when i run the initial code from basic setup:
cd /directory/you/downloaded/synthea/to
java -jar synthea-with-dependencies.jar

it appears to run properly, but then at the end, it shows alive=0 and dead=0 rather than a binary 1,0.
I'm new to java and just using the command prompt window in general, so it's likely user error.  anyone have ideas on how to fix?

This is what shows at the end of the run:
Running with options:
Population: 1
Seed: 1571852739993
Provider Seed:1571852739993
Location: Massachusetts
Min Age: 0
Max Age: 140
java.lang.NullPointerException
        at org.mitre.synthea.engine.State$CallSubmodule.process(State.java:229)
        at org.mitre.synthea.engine.State.run(State.java:159)
        at org.mitre.synthea.engine.Module.process(Module.java:256)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:349)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:259)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
{alive=0, dead=0}

**Comment by dehall** [comment]
I just confirmed the same error running on Windows. On Mac it works as expected.

**Comment by hadleynet** [comment]
Looks like this is a bug in the code that loads sub-modules. Investigating.

**Comment by dehall** [comment]
We've re-generated the with-dependencies jar so everything should be working now. @BYHealthCat  could you try downloading it and trying it again?

**Comment by BYHealthCat** [comment]
@dehall  thank you!  yes, I will re-download and try again this afternoon as soon as I have time.

**Comment by BYHealthCat** [comment]
@dehall   works like a charm.  thank you!
