### ISSUE TITLE
UK example - stack trace

### ISSUE THREAD

**Issue by andyt530** [synthetichealth/synthea#629]
Hi,

If I follow the documented example for other regions (Shrewsbury in the UK) , 

[https://github.com/synthetichealth/synthea/wiki/Other-Areas](https://github.com/synthetichealth/synthea/wiki/Other-Areas)

setting the contents of the zipfile, demographics and hospital csv files as shown 

&  generate.geography.country_code = UK

Then:

run-synthea -s 0 -p 1 "West Midlands" Shrewsbury

I get a stack trace:

java.lang.NullPointerException
        at org.mitre.synthea.world.agents.Person.setProvider(Person.java:529)
        at org.mitre.synthea.world.agents.Person.setProvider(Person.java:542)
        at org.mitre.synthea.world.agents.Person.getProvider(Person.java:520)
        at org.mitre.synthea.world.agents.Person.encounterStart(Person.java:456)
        at org.mitre.synthea.modules.EncounterModule.createEncounter(EncounterModule.java:133)
        at org.mitre.synthea.modules.EncounterModule.process(EncounterModule.java:64)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:347)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:259)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

I also get the same when trying to use my own UK data set as well.

Any hints on how to workaround/fix please ?

Does anyone else get the same ?

**Comment by roylecj** [comment]
I get the same for Australia.

**Comment by jawalonoski** [comment]
Some things have changed since that wiki page was written, especially in regards to filtering and searching providers. I'll try to recreate your error and update the documentation with appropriate changes.

**Comment by meghanaponnuru123** [comment]
I got the same error.

Running with options:
Population: 1
Seed: 0
Location: Shrewsbury, West Midlands
Min Age: 0
Max Age: 140
java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
        at org.mitre.synthea.world.agents.Person.setProvider(Person.java:406)
        at org.mitre.synthea.world.agents.Person.setProvider(Person.java:411)
        at org.mitre.synthea.world.agents.Person.getProvider(Person.java:399)
        at org.mitre.synthea.world.agents.Person.encounterStart(Person.java:336)
        at org.mitre.synthea.modules.EncounterModule.process(EncounterModule.java:62)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:312)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:233)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
{alive=0, dead=0}

**Comment by jawalonoski** [comment]
Apologies for the delay here.

I've updated the Other Areas wiki.... but right now it won't work on the `master` branch. Checkout the `other_area_fixes` branch if you want to try it out. At least until I merge the fixes.

**Comment by jawalonoski** [comment]
The `other_area_fixes` is almost merged in... Also, checkout the synthea-international repository, if anyone wants to submit files for Australia (@roylecj?) or another area.
https://github.com/synthetichealth/synthea-international
