### ISSUE TITLE
testYears FAILED - During gradlew build check test

### ISSUE THREAD

**Issue by DSSDEV-Repo** [synthetichealth/synthea#631]
I just attempted to install Synthea this morning.

When running the "gradlew build check test", I got a LOT of checkstyle warnings, but I also got one failure.

OpenJDK 64-Bit Server VM warning: You have loaded library /root/libj2v8_linux_x86_64.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.

org.mitre.synthea.helpers.UtilitiesTest > testYears FAILED
    java.lang.AssertionError: expected:<75> but was:<74>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.mitre.synthea.helpers.UtilitiesTest.testYears(UtilitiesTest.java:33)

339 tests completed, 1 failed, 1 skipped

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///opt/synthea/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 27m 6s
15 actionable tasks: 15 executed

I am attaching the output logfiles for todays test:

[test_results.tar.gz](https://github.com/synthetichealth/synthea/files/3984570/test_results.tar.gz)

Any help would be much appreciated.

I should also probably mention that I tried to build this in a Docker container.

Have a very Merry Christmas.

**Comment by eedrummer** [comment]
Thanks for the detailed bug report. This is a known issue, and the team is working on a fix. I have proposed #630. The core of the issue is that the code for calculating the length of a year is dropping a quarter of a day to account for leap years. That means the test fails for the later portion of December, but should work in the new year.

We have proposed fixes, but want to ensure that existing code is not reliant on the current behavior.

**Comment by DSSDEV-Repo** [comment]
Thank you for the timely response.

My question to you now would be:  Will the patient generator work as it is, or do I need to wait for your bug fix(es)?

**Comment by DSSDEV-Repo** [comment]
Also, one last question:

I would like to change the output location for both the logfiles, and the reports.

Is there a particular configuration file where I can set these output directories?

And, if it is not clear, what would the syntax be of these entries?

For example, I want to send all output to the /Docker/Synthea/Logs, and /Docker/Synthea/Reports directories.

Thanks for your time, and have a very Merry Christmas.

**Comment by DSSDEV-Repo** [comment]
I sent the previous post, because I found the configuration file.

I changed the parameters inside of this file, but it does not seem to make any difference.

The output files are still writing to the exact same location.

And, the output files are still in the default FHIR JSON format.

Please tell me how to make any changes I make to the config file take effect!

Thanks in advance, and have a very Merry Christmas.

**Comment by DSSDEV-Repo** [comment]
To whom it may concern,

I never received an answer to my previous questions:

1) How can I change the location of the log files?

2) After making changes to some configuration file, somewhere, how do I make the changes persistent?

3) How do I change, or experiment with, the other output types?

I tried changing the output report types inside of the config file, but the reports never changed.

Any help would be much appreciated.

**Comment by eedrummer** [comment]
1. Do you mean the build/test log files?
1. You should be able to create your own configuration file as described in [Common Configuration](https://github.com/synthetichealth/synthea/wiki/Common-Configuration)
1. You need to supply a configuration file that has other exporters turned on. For example, you can set `exporter.ccda.export` to `true` to get CCDA document export.
