### ISSUE TITLE
stack dump for wellness encounters with UK data

### ISSUE THREAD

**Issue by andyt530** [synthetichealth/synthea#671]
Hi 

I have my own UK demographics, zipcodes and hospitals file - but I'm getting this:

Is there a latent issues with wellness encounters for UK based providers ?

Seed: 1583084347117
Provider Seed:1583084347117
Location: Yorkshire
Min Age: 0
Max Age: 140
java.lang.RuntimeException: Unable to find provider: wellness
        at org.mitre.synthea.world.agents.Person.setProvider(Person.java:561)
        at org.mitre.synthea.world.agents.Person.setProvider(Person.java:569)
        at org.mitre.synthea.world.agents.Person.getProvider(Person.java:554)
        at org.mitre.synthea.world.agents.Person.encounterStart(Person.java:476)
        at org.mitre.synthea.modules.EncounterModule.createEncounter(EncounterModule.java:133)
        at org.mitre.synthea.modules.EncounterModule.process(EncounterModule.java:64)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:359)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:275)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
{alive=0, dead=0}

The 3 files i've changed from your UK (synthea-international) example are attached:
[geography-files.zip](https://github.com/synthetichealth/synthea/files/4272188/geography-files.zip)
[providers.zip](https://github.com/synthetichealth/synthea/files/4272189/providers.zip)

(extended zipcodes and demographics for "Yorkshire" in geography.zip)
(Yorkshire hospitals in providers.zip)

Not sure why any of these changes would cause the "wellness" fault above ?

Thanks

Andy

**Comment by jawalonoski** [comment]
@andyt530 So, I downloaded the attachments, but they appear to be the original Shrewsbury files -- I don't see anything about Yorkshire.

The key to making geographic changes is that ALL the data files need to be synchronized.

If you want to model Yorkshire, you need to have Yorkshire (and at least whatever the "state" equivalent is, probably the county of "York") in ALL of the following files:

 - `src/main/resources/geography/demographics_uk.csv`
 - `src/main/resources/geography/timezones_uk.csv`
 - `src/main/resources/geography/zipcodes_uk.csv`
 - `src/main/resources/providers/hospitals_uk.csv`
 - `src/main/resources/providers/primary_care_facilities_uk.csv`
 - `src/main/resources/providers/urgent_care_facilities_uk.csv`

After that, you are probably running synthea with a command like this:

```
./run_synthea [state:required] [city:optional]
```

In your case would be:
```
./run_synthea York Yorkshire
```

**Comment by jawalonoski** [comment]
It has been over a month since this issue was posted without updates, so I am going to assume the original poster solved their problem or moved onto other things.
