### ISSUE TITLE
Unexpected population size in output

### ISSUE THREAD

**Issue by awatson1978** [synthetichealth/synthea#713]
Hello, 
I'm running the following command using the congestive heart failure module:
```
./run_synthea -s 12345 -m *heart* -p 100 Illinois "Chicago"
```

When I inspect the output, 183 patients are being generated.  Interestingly, that number stays the same when I rerun the command with the same seed.  

We're getting a lot of duplicates.  For instance, patient 90 is exported 4 different times....

- Lindsey52 Kunde533
- Eun46 Terry864 
- Devona405 Glover433

```
90 -- Lindsey52 Kunde533 (63 y/o F) Chicago, Illinois DECEASED
95 -- Tasha327 Welch179 (55 y/o F) Chicago, Illinois 
50 -- Charisse42 Monahan736 (54 y/o F) Chicago, Illinois DECEASED
68 -- Wesley533 Hand679 (67 y/o F) Chicago, Illinois DECEASED
23 -- Tyisha680 Turcotte120 (67 y/o F) Chicago, Illinois DECEASED
90 -- Eun46 Terry864 (67 y/o F) Chicago, Illinois DECEASED
68 -- Agnes294 Mayer370 (77 y/o F) Chicago, Illinois 
50 -- Maryann106 Block661 (60 y/o F) Chicago, Illinois DECEASED
23 -- Yasuko490 Daugherty69 (54 y/o F) Chicago, Illinois DECEASED
50 -- Anita473 Bergnaum523 (59 y/o F) Chicago, Illinois DECEASED
90 -- Devona405 Glover433 (69 y/o F) Chicago, Illinois 
23 -- Cary869 Mertz280 (63 y/o F) Chicago, Illinois DECEASED
50 -- Milissa240 Gorczany269 (76 y/o F) Chicago, Illinois DECEASED
23 -- Tenisha328 Friesen796 (62 y/o F) Chicago, Illinois DECEASED
23 -- Arica110 Luettgen772 (70 y/o F) Chicago, Illinois DECEASED
50 -- George991 Bergstrom287 (52 y/o F) Chicago, Illinois DECEASED
50 -- Daysi106 Nienow652 (58 y/o F) Chicago, Illinois DECEASED
23 -- Lavelle273 Shanahan202 (62 y/o F) Chicago, Illinois DECEASED
23 -- Mary779 Stehr398 (62 y/o F) Chicago, Illinois DECEASED
50 -- Sheena120 Wuckert783 (84 y/o F) Chicago, Illinois DECEASED
50 -- Marisa391 Jacobson885 (62 y/o F) Chicago, Illinois DECEASED
50 -- Ferne426 Conn188 (65 y/o F) Chicago, Illinois DECEASED
java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
        at org.mitre.synthea.world.agents.Person.setProvider(Person.java:504)
        at org.mitre.synthea.world.agents.Person.setProvider(Person.java:509)
        at org.mitre.synthea.world.agents.Person.getProvider(Person.java:497)
        at org.mitre.synthea.world.agents.Person.encounterStart(Person.java:434)
        at org.mitre.synthea.modules.EncounterModule.createEncounter(EncounterModule.java:133)
        at org.mitre.synthea.engine.State$Encounter.process(State.java:509)
        at org.mitre.synthea.engine.State.run(State.java:159)
        at org.mitre.synthea.engine.Module.process(Module.java:233)
        at org.mitre.synthea.engine.Module.process(Module.java:245)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:328)
        at org.mitre.synthea.engine.Generator.lambda$run$2(Generator.java:239)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
50 -- Sharyl439 Larkin917 (63 y/o F) Chicago, Illinois DECEASED
50 -- Bebe406 Frami345 (72 y/o F) Chicago, Illinois DECEASED
50 -- Savannah232 Schoen8 (61 y/o F) Chicago, Illinois DECEASED
50 -- Alanna27 Johnson679 (65 y/o F) Chicago, Illinois DECEASED
50 -- Genevieve884 Runolfsdottir785 (66 y/o F) Chicago, Illinois DECEASED
50 -- Joshua658 Spinka232 (62 y/o F) Chicago, Illinois DECEASED
50 -- Ariana988 Schmitt836 (65 y/o F) Chicago, Illinois DECEASED
50 -- Hae300 Johns824 (77 y/o F) Chicago, Illinois DECEASED
```

There's also that `NullPointerException` that gets thrown out a half dozen times during the run.  

Any thoughts on what this all might be?

**Comment by jawalonoski** [comment]
@awatson1978 thank you for reporting this issue. I tried recreating the Null Pointer Exception on both the `master` branch and the `covid19` branch and wasn't able to recreate it.

Given the stack trace, it looks like the software can't find a particular type of provider. This might happen if you changed the provider files, or if we fixed a bug recently.

Maybe try updating Synthea with `git pull`.

In regards to why patient `90` or patient `50` gets generated repeatedly -- because when you says `-p 100` that means _"generate 100 living patients"_ so during the simulation if some of them die along the way, it will attempt to replace the dead patient with a living one (sometimes it needs to try repeatedly which is why you end up with 183). The dead patients are also exported, just in case you want them.

**Comment by awatson1978** [comment]
Resolved.
