### ISSUE TITLE
Evolving Population help appreciated

### ISSUE THREAD

**Issue by AndriesSmartmed** [synthetichealth/synthea#739]
Currently I'm trying to generate evolving vital sign data through the Evolving Population feature at: [https://github.com/synthetichealth/synthea/wiki/Evolving-a-Population]

However I run into an error, how to proceed? (normal Synthea cmd run just fine)  My setup:

Windows .bat file:
`java -jar synthea-with-dependencies.jar ./run_synthea -p 5 -u output/1/snap --exporter.baseDirectory output/1
java -jar synthea-with-dependencies.jar ./run_synthea -i output/1/snap -u output/2/snap -t 100 --exporter.baseDirectory output/2
java -jar synthea-with-dependencies.jar ./run_synthea -i output/2/snap -u output/3/snap -t 100 --exporter.baseDirectory output/3
pause`

Folder structure:  output/1, output/2, output/3 

`Error: Unable to load demographics 
java.lang.Exception: The city output/1/snap was not found in the demographics file.
        at org.mitre.synthea.world.geography.Location.<init>(Location.java:59)
        at org.mitre.synthea.engine.Generator.init(Generator.java:188)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:143)
        at App.main(App.java:144)
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.mitre.synthea.world.geography.Location.<init>(Location.java:81)
        at org.mitre.synthea.engine.Generator.init(Generator.java:188)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:143)
        at App.main(App.java:144)
Caused by: java.lang.Exception: The city output/1/snap was not found in the demographics file.
        at org.mitre.synthea.world.geography.Location.<init>(Location.java:59)
        ... 3 more`

_Originally posted by @AndriesSmartmed in https://github.com/synthetichealth/synthea/issues/716#issuecomment-651059161_

**Comment by jawalonoski** [comment]
Addressed in #716
