### ISSUE TITLE
Enabling physiology generators causes exceptions

### ISSUE THREAD

**Issue by pete-thompson** [synthetichealth/synthea#744]
Setting physiology.generators.enabled = true with a population of more than 1 patient causes exceptions such as:

```
Loading physiology generator configuration "circulation_hemodynamics.yml"
java.lang.NullPointerException
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.expectText(UnmarshallingContext.java:641)
        at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.processText(SAXConnector.java:212)
        at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:162)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:518)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3078)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:836)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:541)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:258)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:229)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:170)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:138)
        at org.opencds.cqf.cql.execution.CqlLibraryReader.read(CqlLibraryReader.java:110)
        at org.opencds.cqf.cql.execution.CqlLibraryReader.read(CqlLibraryReader.java:101)
        at org.mitre.synthea.helpers.ExpressionProcessor.<init>(ExpressionProcessor.java:109)
        at org.mitre.synthea.helpers.physiology.IoMapper.initialize(IoMapper.java:137)
        at org.mitre.synthea.helpers.physiology.IoMapper.initialize(IoMapper.java:127)
        at org.mitre.synthea.helpers.physiology.SimRunner.<init>(SimRunner.java:43)
        at org.mitre.synthea.helpers.PhysiologyValueGenerator.fromConfig(PhysiologyValueGenerator.java:163)
        at org.mitre.synthea.helpers.PhysiologyValueGenerator.fromConfig(PhysiologyValueGenerator.java:148)
        at org.mitre.synthea.helpers.PhysiologyValueGenerator.loadAll(PhysiologyValueGenerator.java:133)
        at org.mitre.synthea.helpers.PhysiologyValueGenerator.loadAll(PhysiologyValueGenerator.java:111)
        at org.mitre.synthea.modules.LifecycleModule.setupVitalSignGenerators(LifecycleModule.java:255)
        at org.mitre.synthea.modules.LifecycleModule.birth(LifecycleModule.java:240)
        at org.mitre.synthea.engine.Generator.createPerson(Generator.java:516)
        at org.mitre.synthea.engine.Generator.generatePerson(Generator.java:395)
        at org.mitre.synthea.engine.Generator.lambda$4(Generator.java:315)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
````

It appears that the cause is that the SQL compiler isn't thread safe. I've created a pull request that places a synchronized block around the compilation step, which fixes the problem for me.

**Comment by jawalonoski** [comment]
Confirmed.
