### ISSUE TITLE
resolveAndExportEncounterCodes test FAILED

### ISSUE THREAD

**Issue by abhairaj** [synthetichealth/synthea#755]
org.mitre.synthea.export.CodeResolveAndExportTest > resolveAndExportEncounterCodes FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.mitre.synthea.export.CodeResolveAndExportTest.tearDown(CodeResolveAndExportTest.java:418)
<

**Comment by jawalonoski** [comment]
Additional information beyond the stack trace would help.

Have you altered any of the default settings before you ran these unit tests?

It looks the failure occurred in the `tearDown` method. Does the output folder exist?

Probably need to refactor this unit test to use a temporary folder instead of the default output folder, in case it already has data there or is otherwise protected.

**Comment by abhairaj** [comment]
Hi Jason. Sorry for not providing more details...

I just cloned the project and ran `gradlew build check test`. `output` does exist.

**Comment by RahatChoudhary** [comment]
Hey guyz. I am also facing the same issue while running this command gradlew build check test. So is there any workaround or solution of it? Kindly let me know.

**Comment by jawalonoski** [comment]
Is the error transient or does the same error occur every time? We haven't had the time to dig into this yet.

**Comment by RahatChoudhary** [comment]
I've tried twice but the same error occurring.
