### ISSUE TITLE
Unable to generate records for GB patients

### ISSUE THREAD

**Issue by philipharfield** [synthetichealth/synthea#759]
Hello,

I'm exploring SYNTHEA for a local application.  I've created modules and done the basics with the software although all the patients are US based.

I've downloaded the GB geography as per the instructions on Github.  i've also confirmed that all the configuration files are being picked up.  But when I specify a state, e.g. Somerset, I get the following error:
c:\Dev\Synthea>java -jar synthea-with-dependencies.jar -c synthea.properties -p 10 Somerset
Exception in thread "main" java.lang.NullPointerException
        at org.mitre.synthea.world.agents.Payer.loadPayers(Payer.java:196)
        at org.mitre.synthea.world.agents.Payer.loadPayers(Payer.java:166)
        at org.mitre.synthea.engine.Generator.init(Generator.java:235)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:170)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:155)
        at App.main(App.java:199)

If I specify a city as well, I can this error:
_c:\Dev\Synthea>java -jar synthea-with-dependencies.jar -c synthea.properties -p 10 Somerset Bristol
ERROR: unable to load demographics
java.lang.Exception: The city Bristol was not found in the demographics file.
        at org.mitre.synthea.world.geography.Location.<init>(Location.java:66)
        at org.mitre.synthea.engine.Generator.init(Generator.java:205)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:170)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:155)
        at App.main(App.java:199)
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.mitre.synthea.world.geography.Location.<init>(Location.java:93)
        at org.mitre.synthea.engine.Generator.init(Generator.java:205)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:170)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:155)
        at App.main(App.java:199)
Caused by: java.lang.Exception: The city Bristol was not found in the demographics file.
        at org.mitre.synthea.world.geography.Location.<init>(Location.java:66)
        ... 4 more

Is this a known bug?  Any suggestions how to resolve?

many thanks,

Phil

**Comment by shabiel** [comment]
There is now a new repo for international users. Here:
https://github.com/synthetichealth/synthea-international.

Take a look and let us know how you fare.

--Sam

**Comment by scivm** [comment]
I think a bug has slipped in for non US generation.  It is getting a null pointer when trying to find the abbreviation for a state name.  I will open separate issue for that one.

The following steps I was able to generate patients for Somerset/Bristol

git clone https://github.com/synthetichealth/synthea
git clone https://github.com/synthetichealth/synthea-international
cd synthea-international
cp -R gb/ ../synthea
cd ../synthea

Edit file ./main/java/org/mitre/synthea/world/agents/Payer.java 196:
      //if (payerStates.contains(abbreviation) || payerStates.contains("*")) {
      if (payerStates.contains("*")) {

./run_synthea -p 5 Somerset Bristol

...
Running with options:
Population: 5
Seed: 1596215455667
Provider Seed:1596215455667
Reference Time: 1596215455667
Location: Bristol, Somerset
Min Age: 0
Max Age: 140
5 -- Andreas188 Mitchell808 (13 y/o M) Bristol, Somerset
3 -- Marcos263 Jaskolski867 (39 y/o M) Bristol, Somerset
2 -- Eddie505 Quitzon246 (53 y/o M) Bristol, Somerset
4 -- Carl856 Gleichner915 (67 y/o M) Bristol, Somerset
1 -- Shantelle354 Bernier607 (65 y/o F) Bristol, Somerset
Records: total=5, alive=5, dead=0

**Comment by scivm** [comment]
I made a lot of edits to my response so please check again and follow the steps outlined for generating Somerset, Bristol.  I did not find any defect except in the README instructions which I am creating a pull request to correct.

**Comment by philipharfield** [comment]
Hi,

Thanks for looking at this.  I had been using the release .jar as I was on a Windows machine.  Building from source and editing the payers.java does create a build that accepts international (GB) geographies.

I'll use this local build until this bug is resolved in the source.
