### ISSUE TITLE
Build failed after syncing up master at 63c5ce3 - Change semver VM (#1523)

### ISSUE THREAD

**Issue by IoTFier** [synthetichealth/synthea#835]
Hello,

My build failed after syncing master at 63c5ce3 - Change semver VM (#1523)

****My env details ** -** 

windows 10 64 bit, jdk
java --version
openjdk 11.0.9 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9+11, mixed mode)
git version 2.17.1.windows.2

![image](https://user-images.githubusercontent.com/26844611/102568770-cd1fdc00-40a9-11eb-9fa9-96bc7fc2eadc.png)

> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.emf.ecore.xmi.impl.XMLHandler (file:/I:/Dev/GitHub/synthea/lib/mdhtruntime/non-mdht/org.eclipse.emf.ecore.xmi-2.12.0.v20160420-0247.jar) to method com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser$LocatorProxy.getEncoding()
WARNING: Please consider reporting this to the maintainers of org.eclipse.emf.ecore.xmi.impl.XMLHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

org.mitre.synthea.helpers.UtilitiesTest > testYears FAILED
    java.lang.AssertionError: expected:<75> but was:<74>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.mitre.synthea.helpers.UtilitiesTest.testYears(UtilitiesTest.java:34)

org.mitre.synthea.world.agents.PersonTest > testPersonRecreationSerialDifferentGenerator FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.mitre.synthea.world.agents.PersonTest.testPersonRecreationSerialDifferentGenerator(PersonTest.java:215)

org.mitre.synthea.world.agents.PersonTest > testPersonFhirSTU3Recreation FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.mitre.synthea.world.agents.PersonTest.testPersonFhirSTU3Recreation(PersonTest.java:355)

org.mitre.synthea.world.agents.PersonTest > testPersonRecreationSerialSameGenerator FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.mitre.synthea.world.agents.PersonTest.testPersonRecreationSerialSameGenerator(PersonTest.java:265)

org.mitre.synthea.world.agents.PersonTest > testPersonFhirR4Recreation FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.mitre.synthea.world.agents.PersonTest.testPersonFhirR4Recreation(PersonTest.java:305)

org.mitre.synthea.world.agents.PersonTest > testPersonCcdaRecreation FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.mitre.synthea.world.agents.PersonTest.testPersonCcdaRecreation(PersonTest.java:455)

org.mitre.synthea.world.agents.PersonTest > testPersonFhirDSTU2Recreation FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.mitre.synthea.world.agents.PersonTest.testPersonFhirDSTU2Recreation(PersonTest.java:405)

462 tests completed, 7 failed, 4 skipped

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///{local path}/synthea/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 41m 48s
15 actionable tasks: 15 executed

**Comment by IoTFier** [comment]
Hi @hadleynet,

Will your fix from 12/18 address these issues ? It will be great if Master gets that update soon.
So far the build is failing.

Thank you

**Comment by IoTFier** [comment]
Hi @hadleynet, @jawalonoski and friends, greeting !

Any clue on how to bypass these tests until an applicable fix or workaround is suggested ?

Thank you

**Comment by dehall** [comment]
Hi @IoTFier, we're still trying to track down the root cause of these test failures. For some reason they only happen on Windows, not on Mac (which most of our team uses). We hope to have a fix this week.

That said, we believe the issue is caused by a specific combination of test parameters, and it only affects the test suite, not the main application. It's definitely disconcerting to see the test suite fail, but unless you are seeing specific issues in output I think you can safely ignore the tests for now.

**Comment by IoTFier** [comment]
Thank @dehall . Greetings!

I appreciate your help.

I will wait till you have some resolution.

Thank you.

**Comment by dehall** [comment]
@IoTFier I just merged a PR to master which should address these issues. There are still some remaining flaky tests, but the ones you were seeing repeatedly should be resolved. Please let us know if you continue to see consistent test failures

**Comment by IoTFier** [comment]
Hi @dehall , greetings and Happy Holidays !
Thank you. 

**BUILD SUCCESSFUL in 27m 24s**
Rest as shown below.


100 warnings

> Task :compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :checkstyleTest
[ant:checkstyle] [WARN] {Repo Path}\src\test\java\org\mitre\synthea\editors\GrowthDataErrorsEditorTest.java:13: Wrong lexicographical order for 'org.junit.Before' import. Should be before 'org.mitre.synthea.world.concepts.HealthRecord'. [CustomImportOrder]
[ant:checkstyle] [WARN] {Repo Path}\src\test\java\org\mitre\synthea\editors\GrowthDataErrorsEditorTest.java:14: Wrong lexicographical order for 'org.junit.Test' import. Should be before 'org.mitre.synthea.world.concepts.HealthRecord'. [CustomImportOrder]
[ant:checkstyle] [WARN] {Repo Path}\src\test\java\org\mitre\synthea\editors\GrowthDataErrorsEditorTest.java:15: Wrong lexicographical order for 'org.mitre.synthea.editors.GrowthDataErrorsEditor' import. Should be before 'org.mitre.synthea.world.concepts.HealthRecord'. [CustomImportOrder]
[ant:checkstyle] [WARN] {Repo Path}\src\test\java\org\mitre\synthea\editors\GrowthDataErrorsEditorTest.java:16: Wrong lexicographical order for 'org.mitre.synthea.world.agents.Person' import. Should be before 'org.mitre.synthea.world.concepts.HealthRecord'. [CustomImportOrder]
[ant:checkstyle] [WARN] {Repo Path}\src\test\java\org\mitre\synthea\editors\GrowthDataErrorsEditorTest.java:19: Wrong lexicographical order for 'java.util.List' import. Should be before 'org.mitre.synthea.world.concepts.HealthRecord'. [CustomImportOrder]
[ant:checkstyle] [WARN] {Repo Path}\src\test\java\org\mitre\synthea\editors\GrowthDataErrorsEditorTest.java:20: Wrong lexicographical order for 'java.util.Random' import. Should be before 'org.mitre.synthea.world.concepts.HealthRecord'. [CustomImportOrder]
[ant:checkstyle] [WARN] {Repo Path}\src\test\java\org\mitre\synthea\editors\GrowthDataErrorsEditorTest.java:22: Import statement for 'org.junit.Assert.*' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line. [CustomImportOrder]
[ant:checkstyle] [WARN] {Repo Path}\src\test\java\org\mitre\synthea\editors\GrowthDataErrorsEditorTest.java:22: Using the '.*' form of import should be avoided - org.junit.Assert.*. [AvoidStarImport]
[ant:checkstyle] [WARN] {Repo Path}\src\test\java\org\mitre\synthea\engine\HealthRecordEditorsTest.java:5: Import statement for 'org.junit.Assert.assertEquals' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line. [CustomImportOrder]
[ant:checkstyle] [WARN] {Repo Path}\src\test\java\org\mitre\synthea\engine\HealthRecordEditorsTest.java:6: Import statement for 'org.junit.Assert.assertNotNull' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line. [CustomImportOrder]
[ant:checkstyle] [WARN] {Repo Path}\src\test\java\org\mitre\synthea\engine\HealthRecordEditorsTest.java:7: Import statement for 'org.junit.Assert.assertNull' is in the wrong order. Should be in the 'STATIC' group, expecting not assigned imports on this line. [CustomImportOrder]
[ant:checkstyle] [WARN] {Repo Path}\src\test\java\org\mitre\synthea\helpers\UtilitiesTest.java:29: Annotation 'Test' should be alone on line. [AnnotationLocationMostCases]
Checkstyle rule violations were found. See the report at: file:///{Repo Path}/build/reports/checkstyle/test.html
Checkstyle files with violations: 3
Checkstyle violations by severity: [warning:12]


> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.reflect.UnsafeReflectionAccessor (file:/{User Directory Path}/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.8.6/9180733b7df8542621dc12e21e87557e8c99b8cb/gson-2.8.6.jar) to field java.util.Random.seed
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.reflect.UnsafeReflectionAccessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

BUILD SUCCESSFUL in 27m 24s
16 actionable tasks: 16 executed
