### ISSUE TITLE
NPE with parameter -p1000 generating single record passes

### ISSUE THREAD

**Issue by podalv** [synthetichealth/synthea#840]
java -jar synthea-with-dependencies.jar -p1000
Exception in thread "main" java.lang.NullPointerException
        at org.mitre.synthea.world.agents.Payer.loadPayers(Payer.java:196)
        at org.mitre.synthea.world.agents.Payer.loadPayers(Payer.java:166)
        at org.mitre.synthea.engine.Generator.init(Generator.java:251)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:187)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:172)
        at App.main(App.java:209)

Error is intermittent this code worked with this parameter before, now it does not. Supplying no parameter passes

**Comment by podalv** [comment]
parameter -p1000 without space produces this error
