### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by IoTFier** [synthetichealth/synthea#889]
Hello,

I am getting out of memory java.lang.OutOfMemoryError when tried to run following command

.\run_synthea.bat -s 10000 -cs 10000 -r 20210519 -a 18-85 Texas Dallas -p 1000 --exporter.baseDirectory=./output/210519/s10000-cs10000-r20210519-with-notes-text--a18-85-Texas-Dallas-p1000/

Synthea.properties (renamed to .txt) file attached. CCDA, fhir, notes, text and text_enounters set to True for FHIR R4

Could not read standard output of command 'C:\Program Files\AdoptOpenJDK\jdk-15.0.1.9-hotspot\bin\java.exe'.
java.lang.OutOfMemoryError: Java heap space
        at java.base/java.nio.HeapCharBuffer.<init>(HeapCharBuffer.java:64)
        at java.base/java.nio.CharBuffer.allocate(CharBuffer.java:361)
        at org.gradle.internal.io.StreamByteBuffer.readAsCharBuffer(StreamByteBuffer.java:177)
        at org.gradle.internal.io.StreamByteBuffer.doReadAsString(StreamByteBuffer.java:168)
        at org.gradle.internal.io.StreamByteBuffer.readAsString(StreamByteBuffer.java:159)
        at org.gradle.internal.io.StreamByteBuffer.readAsString(StreamByteBuffer.java:154)
        at org.gradle.internal.io.LineBufferingOutputStream.flush(LineBufferingOutputStream.java:96)
        at java.base/java.io.PrintStream.flush(PrintStream.java:423)
        at org.gradle.internal.io.LinePerThreadBufferingOutputStream.flush(LinePerThreadBufferingOutputStream.java:83)
        at java.base/java.io.FilterOutputStream.flush(FilterOutputStream.java:153)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:68)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:53)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
<==========---> 80% EXECUTING [3h 7m 58s].ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
<==========---> 80% EXECUTING [21h 37m 18s]hreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:832)
<==========---> 80% EXECUTING [4h 9m 58s]
<==========---> 80% EXECUTING [23h 25m 11s]
<==========---> 80% EXECUTING [1h 13m 51s]
<==========---> 80% EXECUTING [3h 18m 48s]

I would appreciate your help to resolve this issue. 
Thank you

[synthea.properties.txt](https://github.com/synthetichealth/synthea/files/6519253/synthea.properties.txt)

**Comment by jawalonoski** [comment]
Texas is a big state with a lot of data to load (demographics, facilities, etc).

Java has default memory limits, depending on the version.

So, you need to increase the amount of memory available to Java. 

There are a number of ways you can do this.

You can Google `JAVA_OPTS memory` or `increase java memory with gradle.properties`.

Both are valid options.
