### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" 

### ISSUE THREAD

**Issue by citizenrich** [synthetichealth/synthea#910]
Hi folks. I see an error with OpenJDK 16 and using synthea-international example with synthea. I speculate that switching Java versions will sort this out and that this is more about synthea than the international repo (hence posting here). I'm curious about the recommended Java distributions and versions if that is indeed the issue.

Here's the error and steps to reproduce (on macOS):
```
> Task :compileJava
/Users/richard/src/github.com/synthetichealth/synthea/src/main/java/org/mitre/synthea/world/geography/Location.java:159: warning: [removal] Double(double) in Double has been deprecated and marked for removal
          Double sum = averages.getOrDefault(determinant, new Double(0));
                                                          ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning

> Task :run FAILED
WARNING: unable to load SDoH csv: null
java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1393)
        at com.google.common.io.Resources.getResource(Resources.java:194)
        at org.mitre.synthea.helpers.Utilities.readResource(Utilities.java:348)
        at org.mitre.synthea.world.geography.Location.<init>(Location.java:127)
        at org.mitre.synthea.engine.Generator.init(Generator.java:206)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:189)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:174)
        at App.main(App.java:219)
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because the return value of "org.mitre.synthea.world.geography.Location.getAbbreviation(String)" is null
        at org.mitre.synthea.world.agents.Payer.loadPayers(Payer.java:207)
        at org.mitre.synthea.world.agents.Payer.loadPayers(Payer.java:177)
        at org.mitre.synthea.engine.Generator.init(Generator.java:247)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:189)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:174)
        at App.main(App.java:219)

FAILURE: Build failed with an exception.
```

```
$ java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment Homebrew (build 16.0.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 16.0.1+0, mixed mode, sharing)
```

To try to reproduce:
```
git clone https://github.com/synthetichealth/synthea
git clone https://github.com/synthetichealth/synthea-international
cd synthea-international
cp -R example/* ../synthea
cd ../synthea
./run_synthea -p 5
```

**Comment by jawalonoski** [comment]
No, it isn't the Java version.

I need to put a default value in for `generate.geography.sdoh.default_file` just in case it isn't in the `synthea.properties` file.

When you copy over the `synthea-international` version of the `synthea.properties` file it blows away that property and you get the dreaded null pointer exception.

**Comment by jawalonoski** [comment]
Testing a fix now.

**Comment by citizenrich** [comment]
Thanks for the super fast fix. When running on the `gb` example with everything fresh, there's no issue. Doing the same on the plain `example` gives the same error.

```bash
rm -rf synthea
rm -rf synthea-international
git clone https://github.com/synthetichealth/synthea
git clone https://github.com/synthetichealth/synthea-international
cd synthea-international
cp -R gb/* ../synthea
cd ../synthea
./run_synthea -p 5 Somerset Bristol
# above is successful
cd ..
rm -rf synthea
rm -rf synthea-international
git clone https://github.com/synthetichealth/synthea
git clone https://github.com/synthetichealth/synthea-international
cd synthea-international
cp -R example/* ../synthea
cd ../synthea/
./run_synthea -p 5
# this results in the above error
# Also tried with ./run_synthea -p 5 Shrewsbury and ./run_synthea -p 5 Shropshire
```

**Comment by jawalonoski** [comment]
The error (`NullPointerException`) is the same, but the stack trace is totally different.

In this case, the error is that the payer data can't be loaded for Massachusetts -- because you didn't specify a "state" Synthea uses the default. Unfortunately, it isn't get smart enough to know you moved it across the world.

As you stated, you also tried "Shrewsbury" and "Shropshire" -- but neither of those are considered to be a "state" according to how `example` was defined.

In this case `West Midlands` is the "state" -- yes, I know it is not considered a "state" in the UK, but that is how we defined it in `example`.

From the [Other Areas](https://github.com/synthetichealth/synthea/wiki/Other-Areas) example, you can run:

```
./run_synthea -p 1 "West Midlands" Shrewsbury
```
or
```
./run_synthea -p 5 "West Midlands"
```
