### ISSUE TITLE
Failed when generate patients in a state which name consists of more than one words such as "New Jersey"

### ISSUE THREAD

**Issue by Mike2023** [synthetichealth/synthea#939]
Hi, I download Synthea code and build successfully.
It is good when generating patients in states like Texas, Oklahoma, California.
e.g. >run_synthea -p 7 Texas
However, when I change to a state which name consists of more than one words, such as "New Jersey", or "North Dakota", it fails. I tried double quotes around the state name but no luck. Actually all states which names consist of two words fails when I try to generate patients national wide with a batch file.

Is there a special syntax for this?
I tried to search for the issue but have not found one.

Appreciate your help!
Mike
============================================
>run_synthea -p 7 New Jersey

> Task :versionTxt
Warning: unable to create version.txt. Generated records will not indicate which version of Synthea was used to create them.
Cannot run program "git": CreateProcess error=2, The system cannot find the file specified

> Task :run
java.lang.IllegalArgumentException: resource version.txt not found.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
        at com.google.common.io.Resources.getResource(Resources.java:195)
        at org.mitre.synthea.helpers.Utilities.readResource(Utilities.java:348)
        at org.mitre.synthea.helpers.Utilities.getSyntheaVersion(Utilities.java:330)
        at org.mitre.synthea.helpers.Utilities.<clinit>(Utilities.java:323)
        at org.mitre.synthea.world.geography.Location.loadAbbreviations(Location.java:472)
        at org.mitre.synthea.world.geography.Location.<clinit>(Location.java:26)
        at org.mitre.synthea.engine.Generator.init(Generator.java:203)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:196)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:181)
        at App.main(App.java:222)
ERROR: unable to load demographics
java.lang.Exception: The city Jersey was not found in the demographics file.
        at org.mitre.synthea.world.geography.Location.<init>(Location.java:69)
        at org.mitre.synthea.engine.Generator.init(Generator.java:213)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:196)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:181)
        at App.main(App.java:222)
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.mitre.synthea.world.geography.Location.<init>(Location.java:96)
        at org.mitre.synthea.engine.Generator.init(Generator.java:213)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:196)
        at org.mitre.synthea.engine.Generator.<init>(Generator.java:181)
        at App.main(App.java:222)
Caused by: java.lang.Exception: The city Jersey was not found in the demographics file.
        at org.mitre.synthea.world.geography.Location.<init>(Location.java:69)
        ... 4 more

> Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_291\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
4 actionable tasks: 2 executed, 2 up-to-date
======================================================

>run_synthea -p 7 "New Jersey"

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Ding\synthea\build.gradle' line: 251

* What went wrong:
A problem occurred evaluating root project 'synthea'.
> startup failed:
  Script1.groovy: 1: Unexpected input: ''' @ line 1, column 12.
     [ '-p','7','New
                ^

  1 error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s

**Comment by jawalonoski** [comment]
Mike, I am running locally on Mac OS X. In Terminal I run:

```
./run_synthea "New Jersey"
```

Or, any other state with two words wrapped in double-quotes , and it completes just fine.

If you are using Windows `cmd` (and it appears that you are), you probably need some type of quote escaping or something.

**Comment by Mike2023** [comment]
Thank you for your response. 
Yes I am using Windows command prompt.
I have tried almost every possible escapes such as follows \, ^, '', "", etc, but no luck.

**Comment by Mike2023** [comment]
I finally find a correct way to do it.
Thanks
