### ISSUE TITLE
retrieving concepts listing using release jar

### ISSUE THREAD

**Issue by fdefalco** [synthetichealth/synthea#960]
I'm attempting to retrieve the listing of concepts in running modules (which works using ./gradlew concepts) however when attempting to do so using the released jar I get the following error:

ava -cp synthea-with-dependencies.jar org.mitre.synthea.helpers.Concepts false
Performing an inventory of concepts...
Exception in thread "main" java.nio.file.FileSystemNotFoundException
        at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171)
        at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157)
        at java.nio.file.Paths.get(Paths.java:143)
        at org.mitre.synthea.helpers.Utilities.walkAllModules(Utilities.java:435)
        at org.mitre.synthea.helpers.Concepts.getConceptInventory(Concepts.java:73)
        at org.mitre.synthea.helpers.Concepts.main(Concepts.java:49)

Is there a way to perform the inventory on the release jar?

**Comment by jawalonoski** [comment]
@hadleynet Can you take a look at this?

**Comment by hadleynet** [comment]
Will do

**Comment by dehall** [comment]
@hadleynet just FYI this exception sounds familiar -- I think this old PR may be relevant https://github.com/synthetichealth/synthea/pull/557
