### ISSUE TITLE
Build fails | 71fe525 - Merge pull request #973 from synthetichealth/thread-pool-sizing

### ISSUE THREAD

**Issue by IoTFier** [synthetichealth/synthea#983]
I updated my master repo to the latest commit at master - 71fe525 - Merge pull request #973 from synthetichealth/thread-pool-sizing

The build fails with the following error. 

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/26844611/149017161-4ad2d654-3b84-4731-b12e-7b03643e9675.png">

**Comment by IoTFier** [comment]
Hi @eedrummer, build fails after updating master to the latest commit - 0f63ca4 - Merge pull request #970 from synthetichealth/java17

Please see the error below where 3 tests are failing.

> Task :compileTestJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :test

org.mitre.synthea.engine.FixedRecordTest > fixedDemographicsImportTest FAILED
    java.lang.AssertionError: expected:<4> but was:<5>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.mitre.synthea.engine.FixedRecordTest.fixedDemographicsImportTest(FixedRecordTest.java:58)

org.mitre.synthea.export.CCDAExporterTest > testCCDAExport FAILED
    java.lang.AssertionError: Validation of exported CCDA failed: Illegal operation (self.realmCode->isEmpty())|index=54, size=54|index=42, size=42 expected:<0> but was:<3>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.mitre.synthea.export.CCDAExporterTest.testCCDAExport(CCDAExporterTest.java:60)

org.mitre.synthea.world.geography.DemographicsTest > languageFromRaceAndEthnicity FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.mitre.synthea.world.geography.DemographicsTest.languageFromRaceAndEthnicity(DemographicsTest.java:78)

503 tests completed, 3 failed, 4 skipped

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///D:/Dev/GitHub/Synthea/synthea/build/reports/tests/test/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 6m 25s
15 actionable tasks: 15 executed

**Comment by jawalonoski** [comment]
The `org.mitre.synthea.world.geography.DemographicsTest > languageFromRaceAndEthnicity` failure is transient. That test isn't great, to be honest, because

1. it is probabilistic, and the random number generator isn't seeded.
2. it defaults to Philadelphia, and we have been migrating tests to use default cities specified in `src/test/resources/test.properties` in the case of people using international demographics files:

```properties
test_state.default = Massachusetts
test_state.alternative = California

test_town.default = Bedford
test_town.alternative = South Gate
```

**Comment by eedrummer** [comment]
I can update the test to seed the Random and use the test properties demographics.

My goal with the test was to make sure we hit as much of the code as possible, as that method has a ton of different branches. That said, it can still be achieved by just seeding the random.

**Comment by IoTFier** [comment]
@eedrummer , @jawalonoski  - thank you for your notes.

Today the build is failing for only "testCCDAExport" test

100 warnings

> Task :compileTestJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :test

org.mitre.synthea.export.CCDAExporterTest > testCCDAExport FAILED
    java.lang.AssertionError: Validation of exported CCDA failed: Illegal operation (self.realmCode->isEmpty()) expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.mitre.synthea.export.CCDAExporterTest.testCCDAExport(CCDAExporterTest.java:60)

503 tests completed, 1 failed, 4 skipped

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.

**Comment by eedrummer** [comment]
@IoTFier yes. I have seen that fail intermittently too. I'll take a look.

**Comment by IoTFier** [comment]
@eedrummer , @jawalonoski - 
I don't know what the new changes in the code are, but one good thing that I want to share is that - 
On my new PC - [AMD 5950x and DDR4 3600 - 128gb RAM - Nvidia 3080 config] - it takes barely 57 seconds to generate 1000 records for a given city in a State. I am generating CCDA, FHIR, Notes, Text notes and Encounters. 

The build is taking less than 2 mins.
So, thank you for this help.

Results -
----------------------------------------------------------------
Records: total=1172, alive=1000, dead=172

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 57s
4 actionable tasks: 2 executed, 2 up-to-date

**Comment by IoTFier** [comment]
@eedrummer - build is failing with today's update to master 

org.mitre.synthea.export.CCDAExporterTest > testCCDAExport FAILED
    java.lang.AssertionError: Validation of exported CCDA failed: Illegal operation (self.realmCode->isEmpty())|Cannot find operation (excluding(OclVoid)) for the type (Set(TS))|Cannot find operation (excluding(OclVoid)) for the type (Set(TS))|Cannot find operation (excluding(OclVoid)) for the type (Set(TS))|Cannot find operation (excluding(OclVoid)) for the type (Set(TS))|Cannot find operation (excluding(OclVoid)) for the type (Set(TS))|Cannot find operation (excluding(OclVoid)) for the type (Set(TS))|Cannot find operation (excluding(OclVoid)) for the type (Set(TS))|Cannot find operation (excluding(OclVoid)) for the type (Set(TS))|Cannot find operation (excluding(OclVoid)) for the type (Set(TS)) expected:<0> but was:<10>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.mitre.synthea.export.CCDAExporterTest.testCCDAExport(CCDAExporterTest.java:60)

503 tests completed, 1 failed, 4 skipped

> Task :test FAILED

FAILURE: Build failed with an exception.

**Comment by IoTFier** [comment]
Hello @eedrummer,

Since last few commits to master branch - I am seeing a consistent behavior where the first build after pull fails and the subsequent builds successfully.

For example, please see the build output after pulling today's commit - ( f1b56e2 - Merge pull request #1001 from synthetichealth/cvd-codes-fix)

Will you please help me understand the reason for this pattern?

Thank you,

---------------------------------------

> Task :compileTestJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :test

org.mitre.synthea.engine.FixedRecordTest > fixedDemographicsImportTest FAILED
    java.lang.AssertionError: expected:<4> but was:<5>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.mitre.synthea.engine.FixedRecordTest.fixedDemographicsImportTest(FixedRecordTest.java:58)

org.mitre.synthea.export.CCDAExporterTest > testCCDAExport FAILED
    java.lang.AssertionError: Validation of exported CCDA failed: Illegal operation (self.realmCode->isEmpty())|Illegal operation (self.realmCode->isEmpty())|Illegal operation (self.realmCode->isEmpty())|Illegal operation (self.realmCode->isEmpty())|Illegal operation (self.realmCode->isEmpty())|Cannot find operation (excluding(OclVoid)) for the type (Set(TS))|Cannot find operation (excluding(OclVoid)) for the type (Set(TS))|Cannot find operation (excluding(OclVoid)) for the type (Set(TS))|Cannot find operation (excluding(OclVoid)) for the type (Set(TS))|Cannot find operation (excluding(OclVoid)) for the type (Set(TS)) expected:<0> but was:<10>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.mitre.synthea.export.CCDAExporterTest.testCCDAExport(CCDAExporterTest.java:62)

org.mitre.synthea.export.CCDAExporterTest > testExportWithNoPreferredWellnessProvider FAILED
    java.lang.AssertionError: expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.mitre.synthea.export.CCDAExporterTest.testExportWithNoPreferredWellnessProvider(CCDAExporterTest.java:92)

507 tests completed, 3 failed, 5 skipped

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: {file path}/Synthea/synthea/build/reports/tests/test/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4m 52s
15 actionable tasks: 15 executed
{path}synthea  master    羽4m 53.134s    .\gradlew.bat build check test                                            pwsh  10:01:

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 4m 14s
